In [42]:
import numpy as np
empty = np.ones((5,7))
for i in range(3):
    for j in range(4):
        empty[2*i][2*j]=2
print(empty)



[[2. 1. 2. 1. 2. 1. 2.]
 [1. 1. 1. 1. 1. 1. 1.]
 [2. 1. 2. 1. 2. 1. 2.]
 [1. 1. 1. 1. 1. 1. 1.]
 [2. 1. 2. 1. 2. 1. 2.]]


In [43]:
def dessin(a):
    for k in range(len(a[0])):
        print("#", end="")
    print("##")
    for i in a: 
        print("#", end="")
        for j in i:
            if j==2:
                print("*", end="")
            elif j==1:
                print(" ", end="")
            else:
                print("H", end="")
        print("#")
    for k in range(len(a[0])):
        print("#", end="")
    print("##")

In [44]:

def create_empty(a, b):
    empty = np.ones((2*a-1, 2*b-1))
    for i in range(a):
        for j in range(b):
            empty[2*i][2*j]=2
    for i in range(a-1):
        for j in range(b-1):
            empty[2*i+1][2*j+1]=0
    return empty

k=create_empty(4,5)

In [75]:
def add_mur(i1,j1,i2,j2,laby):
    if i1==i2 and abs(j1-j2) == 1:
        laby[2*i1][j1+j2]=0
    if j1==j2 and abs(i1-i2) == 1:
        laby[i1+i2][2*j1]=0
    return laby

def remove_mur(i1,j1,i2,j2,laby):
    if i1==i2 and abs(j1-j2) == 1:
        laby[2*i1][j1+j2]=1
    if j1==j2 and abs(i1-i2) == 1:
        laby[i1+i2][2*j1]=1
    return laby
k=add_mur(2,2,1,2,k)
k=add_mur(1,3,1,4,k)
k=add_mur(2,3,1,3,k)
k=add_mur(2,0,1,0,k)
k=add_mur(0,2,0,1,k)
k=add_mur(0,2,1,2,k)
k=add_mur(0,3,1,3,k)
k=add_mur(1,2,2,2,k)
k=add_mur(1,3,2,3,k)

In [76]:
k

array([[2., 1., 2., 0., 2., 1., 2., 1., 2.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [2., 1., 2., 1., 2., 1., 2., 0., 2.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [2., 1., 2., 0., 2., 1., 2., 0., 2.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [2., 1., 2., 0., 2., 1., 2., 1., 2.]])

In [92]:
dessin(k)

###########
#* *H* * *#
# H HHHHH #
#* * * * *#
#HH HHHHH #
#* *H* *H*#
# H H H H #
#* *H* * *#
###########


In [77]:
def cellulesAdjcentes(laby):
    '''
Cette fonction génère un dictionnaire res qui représente les cellules adjacentes dans un labyrinthe donné laby. Elle fonctionne comme suit :

Paramètre d'entrée : laby, un tableau à deux dimensions représentant le labyrinthe.
Sortie : Un dictionnaire où chaque clé est une paire (i, j) représentant une cellule du labyrinthe et la valeur est une liste des cellules adjacentes à cette cellule.
Explication des étapes :

Initialisation des dimensions :

len_lig et len_col sont calculés en prenant la moitié du nombre de lignes et de colonnes de laby (en divisant par 2 et en ajoutant 1 pour prendre en compte la structure particulière du labyrinthe).
Création du dictionnaire res :

Une boucle double crée un dictionnaire avec des clés (i, j) correspondant aux coordonnées des cellules. Chaque clé a une liste vide comme valeur initiale.
Ajout des voisins adjacents :

La fonction parcourt le labyrinthe et pour chaque cellule (i, j), elle vérifie les cases voisines :
Si la cellule à droite (laby[x][y+1]) ou en bas (laby[x+1][y]) est accessible (indiquée par une valeur de 1 dans laby), la cellule (i, j) sera ajoutée à la liste des voisins de la cellule voisine.
Ce processus est bidirectionnel : si (i, j) est voisin de (i+1, j) ou (i, j+1), alors les deux cellules seront inscrites dans les listes des deux.
Retour : Le dictionnaire res est renvoyé, contenant toutes les informations des cellules adjacentes.
    '''
    res={}
    len_lig = len(laby[1])//2 + 1
    len_col = len(laby)//2 + 1
    for i in range(len_col):
        for j in range(len_lig):
            res[(i,j)]=[]
    #add the close space
    for i in range(len_col):
        for j in range(len_lig):
            x=2*i
            y=2*j
            if i<len_col-1:
                if laby[x+1][y]==1:
                    res[(i,j)].append((i+1,j))
                    res[(i+1,j)].append((i,j))
            if j<len_lig-1:
                if laby[x][y+1]==1:
                    res[(i,j+1)].append((i,j))
                    res[(i,j)].append((i,j+1))
    return res

def cellulesPossible(i,j,laby):
    '''
    Cette fonction permet de déterminer toutes les cellules accessibles à partir de la cellule donnée (i, j) dans le labyrinthe. Elle utilise les informations de la fonction cellulesAdjcentes.

Paramètres d'entrée :

(i, j) : les coordonnées d'une cellule de départ.
laby : le labyrinthe.
Sortie : Une liste contenant toutes les cellules accessibles depuis la cellule (i, j).

Explication des étapes :

Obtention des voisins directs :

La fonction commence par appeler cellulesAdjcentes(laby) pour obtenir les voisins directs de la cellule (i, j) (c’est-à-dire, les cellules adjacentes immédiates).
Ces voisins sont stockés dans la liste res.
Recherche de voisins de voisins (répétée) :

La fonction parcourt récursivement les voisins de chaque cellule pour ajouter d'autres cellules accessibles.
Elle maintient deux listes :
res pour les cellules déjà trouvées.
add pour les nouvelles cellules à ajouter.
Les cellules qui ne sont pas déjà dans res ou add sont ajoutées à la liste add.
La procédure continue jusqu’à ce qu'il n'y ait plus de nouvelles cellules à ajouter (c'est-à-dire que add devient vide).
Retour : La fonction renvoie la liste des cellules accessibles, qui comprend toutes les cellules adjacentes, puis les cellules accessibles indirectement.
    '''
    dic = cellulesAdjcentes(laby)
    p = (i,j)
    res = dic[p]
    add = []
    for p1 in res:
        for p2 in dic[p1]:
            if p2 not in add+res:
                add.append(p2)

    
    added = add[:]
    res += add
    while add != []:
        add = []
        for p1 in added:
            for p2 in dic[p1]:
                if p2 not in add and p2 not in res:
                    add.append(p2)
        added = add[:]
        res += added
    
    return res

In [89]:
def is_laby(k):
    #1. All cells are connected
    if (len(cellulesPossible(0,0,k)) != (len(k)+1)*(len(k[0])+1)/4):
        print("NOT All cells are connected!")
        return False
    
    #2. One possible way:  il existe exactement nm − 1 bordures entre cellules qui ne sont pas des murs 
    n = 0
    for i in k:
        for j in i:
            if j == 1:
                n += 1
    if n != (len(k)+1)*(len(k[0])+1)/4 - 1:
        print("NOT One possible way:  il existe exactement nm − 1 bordures entre cellules qui ne sont pas des murs ")
        return False

    return True

In [90]:
k=remove_mur(1,3,1,4,k)
dessin(k)

###########
#* *H* * *#
# H HHHHH #
#* * * * *#
#HH HHHHH #
#* *H* *H*#
# H H H H #
#* *H* * *#
###########


In [91]:
is_laby(k)

NOT One possible way:  il existe exactement nm − 1 bordures entre cellules qui ne sont pas des murs 


False

In [9]:
dessin(k)

###########
#* *o* * *#
# o o o o #
#* * * *o*#
# o o o o #
#* *o* *o*#
# o o o o #
#* *o* * *#
###########
